package com.musicali.app.data.remote.youtube.model

import kotlinx.serialization.Serializable

// Request models
@Serializable
data class CreatePlaylistRequest(
    val snippet: PlaylistSnippet,
    val status: PlaylistStatus = PlaylistStatus()
)

@Serializable
data class PlaylistSnippet(
    val title: String,
    val description: String = "Generated by MusicAli"
)

@Serializable
data class PlaylistStatus(
    val privacyStatus: String = "private"
)

// Response models
@Serializable
data class PlaylistResponse(
    val id: String,
    val snippet: PlaylistSnippet
)

// playlistItems.insert request
@Serializable
data class AddPlaylistItemRequest(
    val kind: String = "youtube#playlistItem",
    val snippet: PlaylistItemSnippet
)

@Serializable
data class PlaylistItemSnippet(
    val playlistId: String,
    val resourceId: ResourceId
)

@Serializable
data class ResourceId(
    val kind: String = "youtube#video",
    val videoId: String
)

@Serializable
data class PlaylistItemResponse(
    val id: String
)
